# Generated by Django 4.1.4 on 2022-12-31 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_auto_20221230_2223'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='todo',
            name='description',
        ),
        migrations.RemoveField(
            model_name='todo',
            name='private',
        ),
    ]
